import { type FormSectionProps } from "../../types/form/FormSectionProps";
import { Attribute } from "../../types/generated/models";
import {
  type CustomAttributeProps,
  VariablesTypes,
} from "../../types/variables/AttributeColumns";
import { D2I18n } from "dhis2-semis-types";

export function generalDetailsFormData(i18n: D2I18n): FormSectionProps[] {
  return [
    {
      section: i18n.t("General Details"),
      description: "",
      disabled: false,
      fields: [
        {
          id: `code`,
          displayName: i18n.t("Academic year"),
          header: "",
          required: false,
          name: `code`,
          labelName: i18n.t("Academic year"),
          valueType: Attribute.valueType
            .TEXT as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: true,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
        },
        {
          id: `description`,
          displayName: i18n.t("Description"),
          header: "",
          required: false,
          name: i18n.t(`description`),
          labelName: "Description",
          valueType: Attribute.valueType
            .TEXT as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
        },
      ],
    },
    {
      section: i18n.t("Period"),
      description: "",
      disabled: false,
      fields: [
        {
          id: `startDate`,
          displayName: i18n.t("Start date"),
          header: "",
          required: false,
          name: `startDate`,
          labelName: i18n.t("Start date"),
          valueType: Attribute.valueType
            .DATE as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
        },
        {
          id: `endDate`,
          displayName: i18n.t("End date"),
          header: "",
          required: false,
          name: `endDate`,
          labelName: i18n.t("End date"),
          valueType: Attribute.valueType
            .DATE as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
        },
      ],
    },
    {
      section: i18n.t("School days"),
      description: "",
      disabled: false,
      fields: [
        {
          id: `monday`,
          displayName: i18n.t("Monday"),
          header: "",
          required: false,
          name: `monday`,
          labelName: i18n.t("Monday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `tuesday`,
          displayName: i18n.t("Tuesday"),
          header: "",
          required: false,
          name: `tuesday`,
          labelName: i18n.t("Tuesday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `wednesday`,
          displayName: i18n.t("Wednesday"),
          header: "",
          required: false,
          name: `wednesday`,
          labelName: i18n.t("Wednesday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `thursday`,
          displayName: i18n.t("Thursday"),
          header: "",
          required: false,
          name: `thursday`,
          labelName: i18n.t("Thursday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `friday`,
          displayName: i18n.t("Friday"),
          header: "",
          required: false,
          name: `friday`,
          labelName: i18n.t("Friday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `saturday`,
          displayName: i18n.t("Saturday"),
          header: "",
          required: false,
          name: `saturday`,
          labelName: i18n.t("Saturday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
        {
          id: `sunday`,
          displayName: i18n.t("Sunday"),
          header: "",
          required: false,
          name: `sunday`,
          labelName: i18n.t("Sunday"),
          valueType: Attribute.valueType
            .BOOLEAN as unknown as CustomAttributeProps["valueType"],
          visible: true,
          disabled: false,
          pattern: "",
          searchable: false,
          error: false,
          content: "",
          key: "",
          unique: true,
          displayInFilters: true,
          type: VariablesTypes.Attribute,
          radio: false,
        },
      ],
    },
  ];
}
