import { type FormSectionProps } from "../../types/form/FormSectionProps";
import { Attribute } from "../../types/generated/models";
import { type CustomAttributeProps, VariablesTypes } from "../../types/variables/AttributeColumns";

export function generalDetailsFormData(): FormSectionProps[] {
    return [
        {
            section: "General Details",
            description: "",
            disabled: false,
            fields: [
                {
                    id: `code`,
                    displayName: "Academic year",
                    header: "",
                    required: false,
                    name: `code`,
                    labelName: "Academic year",
                    valueType: Attribute.valueType.TEXT as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: true,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute
                },
                {
                    id: `description`,
                    displayName: "Description",
                    header: "",
                    required: false,
                    name: `description`,
                    labelName: "Description",
                    valueType: Attribute.valueType.TEXT as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute
                }
            ]
        },
        {
            section: "Period",
            description: "",
            disabled: false,
            fields: [
                {
                    id: `startDate`,
                    displayName: "Start date",
                    header: "",
                    required: false,
                    name: `startDate`,
                    labelName: "Start date",
                    valueType: Attribute.valueType.DATE as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute
                },
                {
                    id: `endDate`,
                    displayName: "End date",
                    header: "",
                    required: false,
                    name: `endDate`,
                    labelName: "End date",
                    valueType: Attribute.valueType.DATE as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute
                }
            ]
        },
        {
            section: "School days",
            description: "",
            disabled: false,
            fields: [
                {
                    id: `monday`,
                    displayName: "Monday",
                    header: "",
                    required: false,
                    name: `monday`,
                    labelName: "Monday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                },
                {
                    id: `tuesday`,
                    displayName: "Tuesday",
                    header: "",
                    required: false,
                    name: `tuesday`,
                    labelName: "Tuesday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }, {
                    id: `wednesday`,
                    displayName: "Wednesday",
                    header: "",
                    required: false,
                    name: `wednesday`,
                    labelName: "Wednesday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }, {
                    id: `thursday`,
                    displayName: "Thursday",
                    header: "",
                    required: false,
                    name: `thursday`,
                    labelName: "Thursday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }, {
                    id: `friday`,
                    displayName: "Friday",
                    header: "",
                    required: false,
                    name: `friday`,
                    labelName: "Friday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }, {
                    id: `saturday`,
                    displayName: "Saturday",
                    header: "",
                    required: false,
                    name: `saturday`,
                    labelName: "Saturday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }, {
                    id: `sunday`,
                    displayName: "Sunday",
                    header: "",
                    required: false,
                    name: `sunday`,
                    labelName: "Sunday",
                    valueType: Attribute.valueType.BOOLEAN as unknown as CustomAttributeProps["valueType"],
                    visible: true,
                    disabled: false,
                    pattern: '',
                    searchable: false,
                    error: false,
                    content: '',
                    key: "",
                    unique: true,
                    displayInFilters: true,
                    type: VariablesTypes.Attribute,
                    radio: false
                }
            ]
        }
    ]
}
